PRAGMA foreign_keys = ON;
CREATE TABLE producers (id TEXT PRIMARY KEY, name TEXT NOT NULL, region TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE users (id TEXT PRIMARY KEY, email TEXT NOT NULL UNIQUE, name TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('producer','authority','admin')), producer_id TEXT REFERENCES producers(id), password_hash TEXT, created_at TEXT NOT NULL);
CREATE TABLE sessions (token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), expires_at TEXT NOT NULL);
CREATE INDEX sessions_expiry ON sessions(expires_at);
CREATE TABLE apiaries (id TEXT PRIMARY KEY, producer_id TEXT NOT NULL REFERENCES producers(id), name TEXT NOT NULL, location TEXT NOT NULL, latitude REAL NOT NULL, longitude REAL NOT NULL);
CREATE TABLE hives (id TEXT PRIMARY KEY, public_id TEXT NOT NULL UNIQUE, producer_id TEXT NOT NULL REFERENCES producers(id), apiary_id TEXT NOT NULL REFERENCES apiaries(id), name TEXT NOT NULL, species TEXT NOT NULL, queen_age INTEGER NOT NULL, installation_date TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('Healthy','Watch','Alert')), device_token_hash TEXT, created_at TEXT NOT NULL);
CREATE INDEX hives_producer ON hives(producer_id);
CREATE TABLE hive_readings (id TEXT PRIMARY KEY, hive_id TEXT NOT NULL REFERENCES hives(id), temperature REAL NOT NULL, humidity REAL NOT NULL, weight REAL NOT NULL, activity REAL, timestamp TEXT NOT NULL);
CREATE INDEX hive_readings_recent ON hive_readings(hive_id, timestamp DESC);
CREATE TABLE hive_inspections (id TEXT PRIMARY KEY, hive_id TEXT NOT NULL REFERENCES hives(id), inspector TEXT NOT NULL, notes TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE batches (id TEXT PRIMARY KEY, public_id TEXT NOT NULL UNIQUE, producer_id TEXT NOT NULL REFERENCES producers(id), apiary_id TEXT NOT NULL REFERENCES apiaries(id), record_json TEXT NOT NULL, lot_information TEXT NOT NULL, extraction_method TEXT NOT NULL, notes TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'DRAFT' CHECK(status IN ('DRAFT','ANALYZED','ANCHORING','ANCHORED','REVOKED')), is_demo INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL);
CREATE INDEX batches_producer ON batches(producer_id,created_at DESC);
CREATE TABLE batch_hives (batch_id TEXT NOT NULL REFERENCES batches(id), hive_id TEXT NOT NULL REFERENCES hives(id), PRIMARY KEY(batch_id,hive_id));
CREATE TABLE batch_documents (id TEXT PRIMARY KEY, batch_id TEXT REFERENCES batches(id), producer_id TEXT NOT NULL REFERENCES producers(id), object_key TEXT NOT NULL UNIQUE, filename TEXT NOT NULL, content_type TEXT NOT NULL, size INTEGER NOT NULL, digest TEXT NOT NULL, kind TEXT NOT NULL DEFAULT 'certificate', created_at TEXT NOT NULL);
CREATE INDEX documents_batch ON batch_documents(batch_id);
CREATE TABLE ai_assessments (id TEXT PRIMARY KEY, batch_id TEXT NOT NULL REFERENCES batches(id), score INTEGER NOT NULL CHECK(score BETWEEN 0 AND 100), classification TEXT NOT NULL CHECK(classification IN ('LOW','MEDIUM','HIGH')), assessment_json TEXT NOT NULL, digest TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE INDEX assessment_batch ON ai_assessments(batch_id,created_at DESC);
CREATE TABLE blockchain_proofs (id TEXT PRIMARY KEY, batch_id TEXT NOT NULL UNIQUE REFERENCES batches(id), canonical_payload_version TEXT NOT NULL, canonical_payload TEXT NOT NULL, record_hash TEXT NOT NULL, hash_algorithm TEXT NOT NULL DEFAULT 'SHA-256', blockchain_tx_hash TEXT, blockchain_network TEXT NOT NULL, chain_id INTEGER NOT NULL, contract_address TEXT NOT NULL, blockchain_timestamp TEXT, block_number TEXT, status TEXT NOT NULL CHECK(status IN ('PREPARING','BROADCASTING','CONFIRMING','ANCHORED','FAILED')), error TEXT, created_at TEXT NOT NULL);
CREATE TABLE hive_alerts (id TEXT PRIMARY KEY, hive_id TEXT REFERENCES hives(id), batch_id TEXT REFERENCES batches(id), producer_id TEXT NOT NULL REFERENCES producers(id), type TEXT NOT NULL, severity TEXT NOT NULL CHECK(severity IN ('Watch','Alert')), title TEXT NOT NULL, detail TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'OPEN' CHECK(status IN ('OPEN','REVIEWED','RESOLVED')), created_at TEXT NOT NULL, resolved_at TEXT);
CREATE INDEX alerts_open ON hive_alerts(status,created_at DESC);
CREATE UNIQUE INDEX active_batch_alert ON hive_alerts(batch_id,type) WHERE status = 'OPEN' AND batch_id IS NOT NULL;
CREATE UNIQUE INDEX active_hive_alert ON hive_alerts(hive_id,type) WHERE status = 'OPEN' AND hive_id IS NOT NULL;
CREATE TABLE verification_events (id TEXT PRIMARY KEY, batch_id TEXT NOT NULL REFERENCES batches(id), verdict TEXT NOT NULL, current_hash TEXT, anchored_hash TEXT, created_at TEXT NOT NULL);
CREATE INDEX verification_recent ON verification_events(created_at DESC);
CREATE TABLE audit_logs (id TEXT PRIMARY KEY, user_id TEXT REFERENCES users(id), producer_id TEXT REFERENCES producers(id), action TEXT NOT NULL, entity_id TEXT NOT NULL, detail TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE INDEX audit_recent ON audit_logs(producer_id,created_at DESC);
CREATE TABLE authority_reviews (id TEXT PRIMARY KEY, alert_id TEXT NOT NULL REFERENCES hive_alerts(id), reviewer_id TEXT NOT NULL REFERENCES users(id), decision TEXT NOT NULL, notes TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE rate_limits (key TEXT PRIMARY KEY, hits INTEGER NOT NULL, reset_at INTEGER NOT NULL);
