import { lazy, Suspense, useState } from "react";
import { Link, useLocation } from "react-router-dom";
import {
  ArrowUpRight,
  Check,
  FileCheck2,
  Search,
  ShieldCheck,
  ShieldX,
  TriangleAlert,
  Users,
} from "lucide-react";
import { toast } from "sonner";
import { useSWRConfig } from "swr";
import { post, useApi } from "../lib/api";
import {
  Badge,
  Button,
  Empty,
  ErrorState,
  Loading,
  Metric,
  Modal,
  PageHeader,
  Panel,
  SectionLink,
  Status,
} from "../components/ui";
import type { Alert } from "../../../../packages/shared/src/index";
const DataBars = lazy(() =>
  import("../components/Charts").then((m) => ({ default: m.DataBars })),
);
interface Overview {
  metrics: {
    totalRecords: number;
    verifiedRecords: number;
    highRiskRecords: number;
    activeAlerts: number;
    tamperingIncidents: number;
    registeredProducers: number;
  };
  risk: Record<string, string | number>[];
  activity: Record<string, string | number>[];
  trend: Record<string, string | number>[];
  records: Record<string, string | number>[];
  queue: Alert[];
}
export default function Authority() {
  const { data, error, mutate } = useApi<Overview>(
    "/authority/overview",
    15000,
  );
  if (error) return <ErrorState error={error} retry={() => void mutate()} />;
  if (!data) return <Loading />;
  const m = data.metrics;
  return (
    <>
      <PageHeader
        eyebrow="National traceability oversight"
        title="See the risk. Protect the trust."
        description="A focused view of the records and colonies that need human attention."
        action={<Badge tone="green">Authority console</Badge>}
      />
      <div className="metrics-grid six">
        <Metric
          label="Total records"
          value={m.totalRecords}
          icon={<FileCheck2 />}
        />
        <Metric
          label="Last verified authentic"
          value={m.verifiedRecords}
          icon={<ShieldCheck />}
        />
        <Metric
          label="High-risk records"
          value={m.highRiskRecords}
          icon={<TriangleAlert />}
        />
        <Metric
          label="Active alerts"
          value={m.activeAlerts}
          icon={<TriangleAlert />}
        />
        <Metric
          label="Tampering incidents"
          value={m.tamperingIncidents}
          icon={<ShieldX />}
        />
        <Metric
          label="Registered producers"
          value={m.registeredProducers}
          icon={<Users />}
        />
      </div>
      <div className="authority-chart-grid">
        <Panel title="Risk distribution" subtitle="Latest assessment per batch">
          <Suspense fallback={<Loading />}>
            <DataBars
              data={data.risk.map((r) => ({
                ...r,
                color:
                  r.name === "LOW"
                    ? "#839b75"
                    : r.name === "MEDIUM"
                      ? "#dbb24c"
                      : "#c77768",
              }))}
            />
          </Suspense>
        </Panel>
        <Panel title="Public verification" subtitle="Recorded checks by day">
          <Suspense fallback={<Loading />}>
            <DataBars data={data.activity} />
          </Suspense>
        </Panel>
        <Panel title="Alert activity" subtitle="Incidents generated by day">
          <Suspense fallback={<Loading />}>
            <DataBars data={data.trend} color="#c89a5a" />
          </Suspense>
        </Panel>
        <Panel title="Records over time" subtitle="New traceability records">
          <Suspense fallback={<Loading />}>
            <DataBars data={data.records} color="#8d9d8d" />
          </Suspense>
        </Panel>
      </div>
      <Panel
        title="High-priority review queue"
        subtitle="Integrity incidents first, then highest assessed risk"
        action={<SectionLink to="/authority/alerts">All alerts</SectionLink>}
      >
        <AlertsTable alerts={data.queue} />
      </Panel>
      <div className="authority-note">
        <ShieldCheck size={24} />
        <div>
          <h3>Proof is automated. Judgment stays human.</h3>
          <p>
            AI identifies unusual metadata. The blockchain exposes changed
            records. Authorities decide which cases need investigation.
          </p>
        </div>
      </div>
    </>
  );
}
function AlertsTable({
  alerts,
  onReview,
}: {
  alerts: Alert[];
  onReview?: (alert: Alert) => void;
}) {
  return alerts.length ? (
    <div className="table-scroll">
      <table>
        <thead>
          <tr>
            <th>Record / incident</th>
            <th>Producer</th>
            <th>Risk</th>
            <th>Integrity</th>
            <th>Status</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          {alerts.map((a) => (
            <tr key={a.id}>
              <td>
                <div className="alert-record">
                  <span
                    className={`alert-icon ${a.type === "TAMPER" ? "red" : ""}`}
                  >
                    {a.type === "TAMPER" ? (
                      <ShieldX size={18} />
                    ) : (
                      <TriangleAlert size={18} />
                    )}
                  </span>
                  <div>
                    <strong>{a.public_id ?? "Hive telemetry"}</strong>
                    <small>{a.title}</small>
                  </div>
                </div>
              </td>
              <td>{a.producer_name}</td>
              <td>{a.score ?? "—"}</td>
              <td>
                <Badge tone={a.type === "TAMPER" ? "red" : "amber"}>
                  {a.type === "TAMPER" ? "Mismatch" : "Review"}
                </Badge>
              </td>
              <td>
                <Status value={a.status} />
              </td>
              <td>
                {onReview ? (
                  <Button variant="ghost" onClick={() => onReview(a)}>
                    Review
                    <ArrowUpRight size={14} />
                  </Button>
                ) : (
                  <Link className="text-link" to="/authority/alerts">
                    Review
                    <ArrowUpRight size={14} />
                  </Link>
                )}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  ) : (
    <Empty
      title="No cases waiting for review"
      description="New risk and integrity incidents will appear here."
    />
  );
}
export function AuthorityAlerts() {
  const { data, error, mutate } = useApi<Alert[]>("/authority/alerts", 15000);
  const [selected, setSelected] = useState<Alert | null>(null);
  const [filter, setFilter] = useState("OPEN");
  const [busy, setBusy] = useState(false);
  const { mutate: globalMutate } = useSWRConfig();
  if (error) return <ErrorState error={error} />;
  if (!data) return <Loading />;
  return (
    <>
      <PageHeader
        eyebrow="Risk & integrity"
        title="Alerts that deserve attention."
        description="Review the evidence, preserve the investigation, and record a decision."
      />
      <Panel>
        <div className="table-toolbar">
          <div className="segmented">
            {["OPEN", "REVIEWED", "RESOLVED", "ALL"].map((f) => (
              <button
                key={f}
                className={filter === f ? "active" : ""}
                onClick={() => setFilter(f)}
              >
                {f.toLowerCase()}{" "}
                <span>
                  {f === "ALL"
                    ? data.length
                    : data.filter((a) => a.status === f).length}
                </span>
              </button>
            ))}
          </div>
        </div>
        <AlertsTable
          alerts={data.filter((a) => filter === "ALL" || a.status === filter)}
          onReview={setSelected}
        />
      </Panel>
      <Modal
        open={!!selected}
        onOpenChange={(o) => {
          if (!o) setSelected(null);
        }}
        title={selected?.title ?? "Review incident"}
        description="Your decision is appended to the authority review history."
      >
        {selected ? (
          <>
            <Badge tone={selected.type === "TAMPER" ? "red" : "amber"}>
              {selected.type}
            </Badge>
            <p className="review-detail">{selected.detail}</p>
            <dl className="detail-list">
              <div>
                <dt>Producer</dt>
                <dd>{selected.producer_name}</dd>
              </div>
              <div>
                <dt>Recorded</dt>
                <dd>{new Date(selected.created_at).toLocaleString("en-IN")}</dd>
              </div>
            </dl>
            {selected.public_id ? (
              <div className="button-row">
                <Link
                  className="text-link"
                  to={`/batches/${selected.public_id}`}
                >
                  Full batch record
                  <ArrowUpRight size={14} />
                </Link>
                <Link
                  className="text-link"
                  to={`/verify/${selected.public_id}`}
                >
                  Recheck public proof
                  <ArrowUpRight size={14} />
                </Link>
              </div>
            ) : selected.hive_id ? (
              <Link className="text-link" to={`/hives/${selected.hive_id}`}>
                View hive
                <ArrowUpRight size={14} />
              </Link>
            ) : null}
            <form
              onSubmit={async (e) => {
                e.preventDefault();
                const f = new FormData(e.currentTarget);
                setBusy(true);
                try {
                  await post(`/authority/alerts/${selected.id}/review`, {
                    decision: f.get("decision"),
                    notes: f.get("notes"),
                  });
                  await Promise.all([
                    mutate(),
                    globalMutate("/authority/overview"),
                  ]);
                  setSelected(null);
                  toast.success("Authority review recorded");
                } catch (e) {
                  toast.error((e as Error).message);
                } finally {
                  setBusy(false);
                }
              }}
            >
              <label>
                Decision
                <select name="decision">
                  <option value="REVIEWED">
                    Reviewed · follow-up required
                  </option>
                  <option value="RESOLVED">Resolved · evidence reviewed</option>
                </select>
              </label>
              <label>
                Review notes
                <textarea
                  name="notes"
                  minLength={8}
                  maxLength={2000}
                  rows={4}
                  required
                  placeholder="Record the evidence reviewed and your next action."
                />
              </label>
              <Button type="submit" busy={busy}>
                <Check size={16} />
                Record decision
              </Button>
            </form>
          </>
        ) : null}
      </Modal>
    </>
  );
}
interface AuthorityRecord {
  public_id: string;
  status: string;
  created_at: string;
  producer: string;
  score: number | null;
  classification: string | null;
  honey_type: string;
  quantity: number;
  integrity: string | null;
}
export function AuthorityRecords() {
  const { data, error } = useApi<AuthorityRecord[]>("/authority/records");
  const [search, setSearch] = useState("");
  if (error) return <ErrorState error={error} />;
  if (!data) return <Loading />;
  const rows = data.filter((r) =>
    `${r.public_id} ${r.producer} ${r.honey_type}`
      .toLowerCase()
      .includes(search.toLowerCase()),
  );
  return (
    <>
      <PageHeader
        eyebrow="The shared record"
        title="Every batch. One clear view."
        description="Cross-producer traceability records and their most recent verification result."
      />
      <Panel>
        <div className="table-toolbar">
          <strong>{rows.length} records</strong>
          <div className="search-input">
            <Search size={17} />
            <input
              aria-label="Search authority records"
              placeholder="Search record or producer"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
            />
          </div>
        </div>
        <div className="table-scroll">
          <table>
            <thead>
              <tr>
                <th>Record</th>
                <th>Producer</th>
                <th>Honey</th>
                <th>Quantity</th>
                <th>Risk</th>
                <th>Latest integrity</th>
                <th>Proof</th>
              </tr>
            </thead>
            <tbody>
              {rows.map((r) => (
                <tr key={r.public_id}>
                  <td>
                    <Link
                      className="text-link mono"
                      to={`/batches/${r.public_id}`}
                    >
                      {r.public_id}
                      <ArrowUpRight size={14} />
                    </Link>
                  </td>
                  <td>{r.producer}</td>
                  <td>{r.honey_type}</td>
                  <td>{r.quantity} kg</td>
                  <td>
                    {r.score ?? "—"}{" "}
                    {r.classification ? (
                      <Status value={r.classification} />
                    ) : null}
                  </td>
                  <td>
                    {r.integrity ? (
                      <Status value={r.integrity} />
                    ) : (
                      <span className="muted">Not checked</span>
                    )}
                  </td>
                  <td>
                    <Status value={r.status} />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Panel>
    </>
  );
}
